### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mehrdadashtari** [p3ym4n/jdate#6]
Hi, I have a suggestion to add event feature

Now that all the systems are connected to the Internet, I suggest you implement the connection with the calendar APIs, in this good source as well.
I use this service a lot myself
https://apieco.ir/api/farsicalendar

Provides good information such as events by day and receive events in solar, lunar and Gregorian mode.

**Comment by p3ym4n** [comment]
First of all sorry for my late reply,
Second, TBH I don't think it's on the same domain of this package.
Thanks for your suggestion.
